# try:
#     x = 5/0
# except Exception as err:
#     print(err.__class__)
#     print(err)

